CREATE TABLE `user` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名',
    `password` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
    `avatar` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '头像',
    `last_sign_in_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后登录时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户信息表';

CREATE TABLE `user_sign_in` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户',
    `ip_address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'IP 地址',
    `sign_in_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登录时间',
    PRIMARY KEY (`id`),
    KEY `idx_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户登录记录表';

CREATE TABLE IF NOT EXISTS `circle_posts`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `uid` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户id',
    `content` VARCHAR(600) DEFAULT '' COMMENT '动态类容',
    `images` VARCHAR(512) DEFAULT '' COMMENT '动态图片',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='圈子动态';

CREATE TABLE IF NOT EXISTS `circle_comments`(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `post_id` BIGINT(20) UNSIGNED NOT NULL COMMENT '圈子动态id',
    `uid` BIGINT(20) UNSIGNED NOT NULL COMMENT '评论用户id',
    `reply_uid` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '被回复用户id',
    `content` VARCHAR(600) DEFAULT '' COMMENT '动态类容'，
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='圈子动态评论';