user:
  method    : POST
  path      : /user
  controller: Dolphin\Ting\Http\Controller\UserController:getUser
userList:
  method    : POST
  path      : /users
  controller: Dolphin\Ting\Http\Controller\UserController:getUserList
userSignIn:
  method    : POST
  path      : /signin
  controller: Dolphin\Ting\Http\Controller\UserController:signIn
userInfo:
  method    : GET
  path      : /userinfo
  controller: Dolphin\Ting\Http\Service\UserService:getUserInfo
uploadToken:
  method    : GET
  path      : /api/uploadtoken
  controller: Dolphin\Ting\Http\Service\FileService:getUploadToken
circle:
  method    : POST
  path      : /api/circle/add
  controller: Dolphin\Ting\Http\Service\CircleService:add
