<?php

namespace Dolphin\Ting\Http\Modules;

use Psr\Container\ContainerInterface as Container;

class OrderModule extends Module
{
    public function getOrderList()
    {
        $orderList = [
            [
                "id" => 1,
                "no" => "755067202001181805428750",
                "outer_id" => null,
                "pickup_no" => "8191",
                "pickup_code_qrcode" => "http://go.heytea.com/orders/755067202001181805428750/puckupNo",
                "pickup_type" => "\u81ea\u63d0",
                "total_fee" => "50.00",
                "box_fee" => "0.00",
                "delivery_fee" => "0.00",
                "discount_fee" => "0.00",
                "coupon_fee" => "0.00",
                "payment" => "50.00",
                "currency_type" => "CNY",
                "paid_at" => "2020-01-18 18:05:50",
                "called_at" => "2020-01-18 18:27:34",
                "status" => "TRADE_CLOSED",
                "refund_status" => "NO_REFUND",
                "reason" => "\u534f\u5546\u4e00\u81f4\u9000\u6b3e",
                "pickup_time" => "2020-01-18 18=>49=>32",
                "pickup_time_period" => "",
                "pickup_time_period_show" => null,
                "takeaway_time_immediately_show" => "2020-01-18 18:50:50",
                "is_takeaway" => false,
                "created_at" => "2020-01-18 18:05:43",
                "remarks" => "\u4e0d\u6253\u5305",
                "coupon_library_id" => "",
                "activity" => [],
                "is_comment" => 2,
                "only_vip_show_invoice" => false,
                "hidden_invoice" => false,
                "invoice_successed" => false,
                "show_remind_button" => 0,
                "order_detail_qrcode" => "https://go.heytea.com/device/755067202001181805428749/order",
                "making_order_count" => 0,
                "need_wait_time" => 0,
                "prior" => 0,
                "trade_type" => "JSAPI",
                "cupboard" => null,
                "is_can_refund" => false,
                "is_premade" => false,
                "gather_feedback" => false,
                "currency" => 1,
                "tax_fee" => "-1",
                "cancelCountdown" => 0,
                "order_channel" => "W",
                "open_pickupPage_expectTime" => 1,
                "alipay_invoice_button" => true,
                "new_order_invoice" => true,
                "set_items" => [],
                "showPaymentDetails" => false,
                "items" => [
                    [
                        "id" => 1,
                        "product_id" => 551,
                        "sku_id" => 1420,
                        "category_id" => 11,
                        "quantity" => 2,
                        "total_fee" => "25.00",
                        "price" => "25.00",
                        "name" => "流心奶黄波波冰",
                        "sname" => "流心奶黄波波冰",
                        "activity_name" => "",
                        "discount_price" => 0,
                        "show_trademark" => false,
                        "name_image" => "",
                        "activity_type" => 0,
                        "specifications" => [],
                        "attributes" => [],
                        "materials" => [
                            [
                                "material_id" => 140,
                                "name" => "冰沙（推荐）",
                                "price" => "0.00",
                                "material_group_id" => 5
                            ],
                            [
                                "material_id" => 33,
                                "name" => "少少冰",
                                "price" => "0.00",
                                "material_group_id" => 3
                            ],
                            [
                                "material_id" => 409,
                                "name" => "\u5e38\u89c4\u5438\u7ba1",
                                "price" => "0.00",
                                "material_group_id" => 27
                            ],
                            [
                                "material_id" => 68,
                                "name" => "\u6b63\u5e38\u7cd6(\u63a8\u8350)",
                                "price" => "0.00",
                                "material_group_id" => 4
                            ],
                            [
                                "material_id" => 149,
                                "name" => "\u6807\u51c6\uff08\u63a8\u8350\uff09",
                                "price" => "0.00",
                                "material_group_id" => 6
                            ]
                        ],
                        "image" => "https=>//go.cdn.heytea.com/product/2019/08/23/tmp/606742485b404725bcc5fe37330c4cde.jpg"
                    ]
                ],
                "shop" => [
                    "id" => 308,
                    "name" => "益田假日天地GO店",
                    "contact_phone" => "0755-27906072",
                    "contact_name" => "\u559c\u8336",
                    "province" => "\u5e7f\u4e1c\u7701",
                    "city" => "\u6df1\u5733\u5e02",
                    "city_code" => "156440300",
                    "district" => "\u5b9d\u5b89\u533a",
                    "address" => "广深路福永段77号1层L1-W55号",
                    "latitude" => "22.66992",
                    "longitude" => "113.827609",
                    "min_charge" => 30,
                    "distance" => 0,
                    "delivery_distance" => 3000,
                    "support_mt_takeaway" => 0,
                    "support_sf_takeaway" => 1,
                    "support_td_takeaway" => 0,
                    "support_jd_takeaway" => 0,
                    "scene_code" => "http：//go.heytea.com/storage/shop/scene_code/shop_id_308.jpg",
                    "tips" => "15",
                    "limit_cup" => 50,
                    "takeaway_limit_cup" => "5",
                    "location_city" => null,
                    "disable_order_type" => 2,
                    "country" => "\u4e2d\u56fd",
                    "country_code" => "156",
                    "district_code" => "440306",
                    "support_cash" => 1,
                    "nearby_shop_count" => 0,
                    "is_current_city" => null,
                    "is_support_premade" => 0,
                    "currency" => 1,
                    "estimate_time_type" => 1,
                    "appointable" => null
                ],
                "delivery" => null
            ],
            [
                "id" => 2,
                "no" => "755067201911061936067635",
                "outer_id" => null,
                "pickup_no" => "8167",
                "pickup_code_qrcode" => "http://go.heytea.com/orders/755067201911061936067635/puckupNo",
                "pickup_type" => "自提",
                "total_fee" => "10.00",
                "box_fee" => "0.00",
                "delivery_fee" => "0.00",
                "discount_fee" => "0.00",
                "coupon_fee" => "0.00",
                "payment" => "10.00",
                "currency_type" => "CNY",
                "paid_at" => "2019-11-06 19=>36=>11",
                "called_at" => "2019-11-06 19=>38=>16",
                "status" => "TRADE_CLOSED",
                "refund_status" => "NO_REFUND",
                "reason" => "\u534f\u5546\u4e00\u81f4\u9000\u6b3e",
                "pickup_time" => "2019-11-06 19=>39=>03",
                "pickup_time_period" => "",
                "pickup_time_period_show" => null,
                "takeaway_time_immediately_show" => "2019-11-06 20=>21=>11",
                "is_takeaway" => false,
                "created_at" => "2019-11-06 19=>36=>06",
                "remarks" => "\u4e0d\u6253\u5305",
                "coupon_library_id" => "",
                "activity" => [],
                "is_comment" => 2,
                "only_vip_show_invoice" => false,
                "hidden_invoice" => false,
                "invoice_successed" => false,
                "show_remind_button" => 0,
                "order_detail_qrcode" => "https://go.heytea.com/device/755067201911061936067635/order",
                "making_order_count" => 0,
                "need_wait_time" => 0,
                "prior" => 0,
                "trade_type" => "JSAPI",
                "cupboard" => null,
                "is_can_refund" => false,
                "is_premade" => false,
                "gather_feedback" => false,
                "currency" => 1,
                "tax_fee" => "1.15",
                "cancelCountdown" => 0,
                "order_channel" => "W",
                "open_pickupPage_expectTime" => 1,
                "alipay_invoice_button" => true,
                "new_order_invoice" => false,
                "set_items" => [],
                "showPaymentDetails" => false,
                "items" => [
                    [
                        "id" => 106805414,
                        "product_id" => 161,
                        "sku_id" => 1186,
                        "category_id" => 20,
                        "quantity" => 1,
                        "total_fee" => "10.00",
                        "price" => "10.00",
                        "name" => "流沙牛角",
                        "sname" => "流沙牛角",
                        "activity_name" => "",
                        "discount_price" => 0,
                        "show_trademark" => false,
                        "name_image" => "",
                        "activity_type" => 0,
                        "specifications" => [],
                        "attributes" => [],
                        "materials" => [
                            [
                                "material_id" => 41,
                                "name" => "加热(推荐)",
                                "price" => "0.00",
                                "material_group_id" => 3
                            ]
                        ],
                        "image" => "https://go.cdn.heytea.com/storage/product/2019/11/12/5ad4996d0fdd4f3a85a25b8fe95a4db8.jpg"
                    ]
                ],
                "shop" => [
                    "id" => 308,
                    "name" => "益田假日天地GO店",
                    "contact_phone" => "0755-27906072",
                    "contact_name" => "\u559c\u8336",
                    "province" => "\u5e7f\u4e1c\u7701",
                    "city" => "\u6df1\u5733\u5e02",
                    "city_code" => "156440300",
                    "district" => "\u5b9d\u5b89\u533a",
                    "address" => "广深路福永段77号1层L1-W55号",
                    "latitude" => "22.66992",
                    "longitude" => "113.827609",
                    "min_charge" => 30,
                    "distance" => 0,
                    "delivery_distance" => 3000,
                    "support_mt_takeaway" => 0,
                    "support_sf_takeaway" => 1,
                    "support_td_takeaway" => 0,
                    "support_jd_takeaway" => 0,
                    "scene_code" => "http://go.heytea.com/storage/shop/scene_code/shop_id_308.jpg",
                    "tips" => "15",
                    "limit_cup" => 50,
                    "takeaway_limit_cup" => "5",
                    "location_city" => null,
                    "disable_order_type" => 2,
                    "country" => "\u4e2d\u56fd",
                    "country_code" => "156",
                    "district_code" => "440306",
                    "support_cash" => 1,
                    "nearby_shop_count" => 0,
                    "is_current_city" => null,
                    "is_support_premade" => 0,
                    "currency" => 1,
                    "estimate_time_type" => 1,
                    "appointable" => null
                ],
                "delivery" => null
            ],
            [
                "id" => 3,
                "no" => "755067201911061932051221",
                "outer_id" => null,
                "pickup_no" => "8165",
                "pickup_code_qrcode" => "http://go.heytea.com/orders/755067201911061932051221/puckupNo",
                "pickup_type" => "\u81ea\u63d0",
                "total_fee" => "28.00",
                "box_fee" => "0.00",
                "delivery_fee" => "0.00",
                "discount_fee" => "0.00",
                "coupon_fee" => "0.00",
                "payment" => "28.00",
                "currency_type" => "CNY",
                "paid_at" => "2019-11-06 19=>32=>11",
                "called_at" => "2019-11-06 19=>43=>36",
                "status" => "TRADE_CLOSED",
                "refund_status" => "NO_REFUND",
                "reason" => "\u534f\u5546\u4e00\u81f4\u9000\u6b3e",
                "pickup_time" => "2019-11-06 19=>54=>35",
                "pickup_time_period" => "",
                "pickup_time_period_show" => null,
                "takeaway_time_immediately_show" => "2019-11-06 20=>17=>11",
                "is_takeaway" => false,
                "created_at" => "2019-11-06 19=>32=>05",
                "remarks" => "\u4e0d\u6253\u5305",
                "coupon_library_id" => "",
                "activity" => [],
                "is_comment" => 2,
                "only_vip_show_invoice" => false,
                "hidden_invoice" => false,
                "invoice_successed" => false,
                "show_remind_button" => 0,
                "order_detail_qrcode" => "https://go.heytea.com/device/755067201911061932051221/order",
                "making_order_count" => 0,
                "need_wait_time" => 0,
                "prior" => 0,
                "trade_type" => "JSAPI",
                "cupboard" => null,
                "is_can_refund" => false,
                "is_premade" => false,
                "gather_feedback" => false,
                "currency" => 1,
                "tax_fee" => "1.58",
                "cancelCountdown" => 0,
                "order_channel" => "W",
                "open_pickupPage_expectTime" => 1,
                "alipay_invoice_button" => true,
                "new_order_invoice" => false,
                "set_items" => [],
                "showPaymentDetails" => false,
                "items" => [
                    [
                        "id" => 106803531,
                        "product_id" => 660,
                        "sku_id" => 1590,
                        "category_id" => 12,
                        "quantity" => 1,
                        "total_fee" => "28.00",
                        "price" => "28.00",
                        "name" => "捣蛋南瓜波波冰",
                        "sname" => "捣蛋南瓜波波冰",
                        "activity_name" => "",
                        "discount_price" => 0,
                        "show_trademark" => false,
                        "name_image" => "",
                        "activity_type" => 0,
                        "specifications" => [],
                        "attributes" => [],
                        "materials" => [
                            [
                                "material_id" => 409,
                                "name" => "常规吸管",
                                "price" => "0.00",
                                "material_group_id" => 27
                            ],
                            [
                                "material_id" => 149,
                                "name" => "\u6807\u51c6\uff08\u63a8\u8350\uff09",
                                "price" => "0.00",
                                "material_group_id" => 6
                            ],
                            [
                                "material_id" => 140,
                                "name" => "\u51b0\u6c99\uff08\u63a8\u8350\uff09",
                                "price" => "0.00",
                                "material_group_id" => 5
                            ],
                            [
                                "material_id" => 48,
                                "name" => "\u5c11\u7cd6",
                                "price" => "0.00",
                                "material_group_id" => 4
                            ],
                            [
                                "material_id" => 558,
                                "name" => "\u6b63\u5e38(\u63a8\u8350)",
                                "price" => "0.00",
                                "material_group_id" => 3
                            ]
                        ],
                        "image" => "https://go.cdn.heytea.com/storage/product/2019/10/29/bac9cab39825405f9b80dac17027aff2.jpg"
                    ]
                ],
                "shop" => [
                    "id" => 308,
                    "name" => "益田假日天地GO店",
                    "contact_phone" => "0755-27906072",
                    "contact_name" => "\u559c\u8336",
                    "province" => "\u5e7f\u4e1c\u7701",
                    "city" => "\u6df1\u5733\u5e02",
                    "city_code" => "156440300",
                    "district" => "\u5b9d\u5b89\u533a",
                    "address" => "\u5e7f\u6df1\u8def\u798f\u6c38\u6bb577\u53f71\u5c42L1-W55\u53f7",
                    "latitude" => "22.66992",
                    "longitude" => "113.827609",
                    "min_charge" => 30,
                    "distance" => 0,
                    "delivery_distance" => 3000,
                    "support_mt_takeaway" => 0,
                    "support_sf_takeaway" => 1,
                    "support_td_takeaway" => 0,
                    "support_jd_takeaway" => 0,
                    "scene_code" => "http://go.heytea.com/storage/shop/scene_code/shop_id_308.jpg",
                    "tips" => "15",
                    "limit_cup" => 50,
                    "takeaway_limit_cup" => "5",
                    "location_city" => null,
                    "disable_order_type" => 2,
                    "country" => "\u4e2d\u56fd",
                    "country_code" => "156",
                    "district_code" => "440306",
                    "support_cash" => 1,
                    "nearby_shop_count" => 0,
                    "is_current_city" => null,
                    "is_support_premade" => 0,
                    "currency" => 1,
                    "estimate_time_type" => 1,
                    "appointable" => null
                ],
                "delivery" => null
            ],
            [
                "id" => 4,
                "no" => "755067201911061931525054",
                "outer_id" => null,
                "pickup_no" => "",
                "pickup_code_qrcode" => "http://go.heytea.com/orders/755067201911061931525054/puckupNo",
                "pickup_type" => "\u81ea\u63d0",
                "total_fee" => "28.00",
                "box_fee" => "0.00",
                "delivery_fee" => "0.00",
                "discount_fee" => "0.00",
                "coupon_fee" => "0.00",
                "payment" => "28.00",
                "currency_type" => "CNY",
                "paid_at" => null,
                "called_at" => null,
                "status" => "CANCELED",
                "refund_status" => "NO_REFUND",
                "reason" => "\u534f\u5546\u4e00\u81f4\u9000\u6b3e",
                "pickup_time" => null,
                "pickup_time_period" => "",
                "pickup_time_period_show" => null,
                "takeaway_time_immediately_show" => "2020-05-25 23=>56=>36",
                "is_takeaway" => false,
                "created_at" => "2019-11-06 19=>31=>52",
                "remarks" => "\u4e0d\u6253\u5305",
                "coupon_library_id" => "",
                "activity" => [],
                "is_comment" => 2,
                "only_vip_show_invoice" => false,
                "hidden_invoice" => false,
                "invoice_successed" => false,
                "show_remind_button" => 0,
                "order_detail_qrcode" => "https://go.heytea.com/device/755067201911061931525054/order",
                "making_order_count" => 0,
                "need_wait_time" => 0,
                "prior" => 0,
                "trade_type" => "JSAPI",
                "cupboard" => null,
                "is_can_refund" => false,
                "is_premade" => false,
                "gather_feedback" => false,
                "currency" => 1,
                "tax_fee" => "1.58",
                "cancelCountdown" => 0,
                "order_channel" => "W",
                "open_pickupPage_expectTime" => 1,
                "alipay_invoice_button" => true,
                "new_order_invoice" => false,
                "set_items" => [],
                "showPaymentDetails" => false,
                "items" => [
                    [
                        "id" => 106803458,
                        "product_id" => 660,
                        "sku_id" => 1590,
                        "category_id" => 12,
                        "quantity" => 1,
                        "total_fee" => "28.00",
                        "price" => "28.00",
                        "name" => "捣蛋南瓜波波冰",
                        "sname" => "捣蛋南瓜波波冰",
                        "activity_name" => "",
                        "discount_price" => 0,
                        "show_trademark" => false,
                        "name_image" => "",
                        "activity_type" => 0,
                        "specifications" => [],
                        "attributes" => [],
                        "materials" => [
                            [
                                "material_id" => 409,
                                "name" => "常规吸管",
                                "price" => "0.00",
                                "material_group_id" => 27
                            ],
                            [
                                "material_id" => 149,
                                "name" => "\u6807\u51c6\uff08\u63a8\u8350\uff09",
                                "price" => "0.00",
                                "material_group_id" => 6
                            ],
                            [
                                "material_id" => 140,
                                "name" => "\u51b0\u6c99\uff08\u63a8\u8350\uff09",
                                "price" => "0.00",
                                "material_group_id" => 5
                            ],
                            [
                                "material_id" => 48,
                                "name" => "\u5c11\u7cd6",
                                "price" => "0.00",
                                "material_group_id" => 4
                            ],
                            [
                                "material_id" => 558,
                                "name" => "\u6b63\u5e38(\u63a8\u8350)",
                                "price" => "0.00",
                                "material_group_id" => 3
                            ]
                        ],
                        "image" => "https://go.cdn.heytea.com/storage/product/2019/10/29/bac9cab39825405f9b80dac17027aff2.jpg"
                    ]
                ],
                "shop" => [
                    "id" => 308,
                    "name" => "益田假日天地GO店",
                    "contact_phone" => "0755-27906072",
                    "contact_name" => "\u559c\u8336",
                    "province" => "\u5e7f\u4e1c\u7701",
                    "city" => "\u6df1\u5733\u5e02",
                    "city_code" => "156440300",
                    "district" => "\u5b9d\u5b89\u533a",
                    "address" => "\u5e7f\u6df1\u8def\u798f\u6c38\u6bb577\u53f71\u5c42L1-W55\u53f7",
                    "latitude" => "22.66992",
                    "longitude" => "113.827609",
                    "min_charge" => 30,
                    "distance" => 0,
                    "delivery_distance" => 3000,
                    "support_mt_takeaway" => 0,
                    "support_sf_takeaway" => 1,
                    "support_td_takeaway" => 0,
                    "support_jd_takeaway" => 0,
                    "scene_code" => "http://go.heytea.com/storage/shop/scene_code/shop_id_308.jpg",
                    "tips" => "15",
                    "limit_cup" => 50,
                    "takeaway_limit_cup" => "5",
                    "location_city" => null,
                    "disable_order_type" => 2,
                    "country" => "\u4e2d\u56fd",
                    "country_code" => "156",
                    "district_code" => "440306",
                    "support_cash" => 1,
                    "nearby_shop_count" => 0,
                    "is_current_city" => null,
                    "is_support_premade" => 0,
                    "currency" => 1,
                    "estimate_time_type" => 1,
                    "appointable" => null
                ],
                "delivery" => null
            ],
            [
                "id" => 5,
                "no" => "755015201910201229255436",
                "outer_id" => null,
                "pickup_no" => "8114",
                "pickup_code_qrcode" => "http://go.heytea.com/orders/755015201910201229255436/puckupNo",
                "pickup_type" => "\u81ea\u63d0",
                "total_fee" => "33.00",
                "box_fee" => "0.00",
                "delivery_fee" => "0.00",
                "discount_fee" => "0.00",
                "coupon_fee" => "0.00",
                "payment" => "33.00",
                "currency_type" => "CNY",
                "paid_at" => "2019-10-20 12=>29=>29",
                "called_at" => "2019-10-20 12=>51=>15",
                "status" => "TRADE_CLOSED",
                "refund_status" => "NO_REFUND",
                "reason" => "\u534f\u5546\u4e00\u81f4\u9000\u6b3e",
                "pickup_time" => "2019-10-20 14=>00=>47",
                "pickup_time_period" => "",
                "pickup_time_period_show" => null,
                "takeaway_time_immediately_show" => "2019-10-20 13=>14=>29",
                "is_takeaway" => false,
                "created_at" => "2019-10-20 12=>29=>25",
                "remarks" => "\u4e0d\u6253\u5305",
                "coupon_library_id" => "",
                "activity" => [],
                "is_comment" => 2,
                "only_vip_show_invoice" => false,
                "hidden_invoice" => false,
                "invoice_successed" => false,
                "show_remind_button" => 0,
                "order_detail_qrcode" => "https://go.heytea.com/device/755015201910201229255436/order",
                "making_order_count" => 0,
                "need_wait_time" => 0,
                "prior" => 0,
                "trade_type" => "JSAPI",
                "cupboard" => null,
                "is_can_refund" => false,
                "is_premade" => false,
                "gather_feedback" => false,
                "currency" => 1,
                "tax_fee" => "-1",
                "cancelCountdown" => 0,
                "order_channel" => "W",
                "open_pickupPage_expectTime" => 1,
                "alipay_invoice_button" => true,
                "new_order_invoice" => false,
                "set_items" => [],
                "showPaymentDetails" => false,
                "items" => [
                    [
                        "id" => 100194060,
                        "product_id" => 161,
                        "sku_id" => 1186,
                        "category_id" => 20,
                        "quantity" => 1,
                        "total_fee" => "10.00",
                        "price" => "10.00",
                        "name" => "流沙牛角",
                        "sname" => "流沙牛角",
                        "activity_name" => "",
                        "discount_price" => 0,
                        "show_trademark" => false,
                        "name_image" => "",
                        "activity_type" => 0,
                        "specifications" => [],
                        "attributes" => [],
                        "materials" => [
                            [
                                "material_id" => 41,
                                "name" => "\u52a0\u70ed(\u63a8\u8350)",
                                "price" => "0.00",
                                "material_group_id" => 3
                            ]
                        ],
                        "image" => "https://go.cdn.heytea.com/storage/product/2019/11/12/5ad4996d0fdd4f3a85a25b8fe95a4db8.jpg"
                    ],
                    [
                        "id" => 100194061,
                        "product_id" => 514,
                        "sku_id" => 1373,
                        "category_id" => 11,
                        "quantity" => 1,
                        "total_fee" => "23.00",
                        "price" => "23.00",
                        "name" => "爆芋泥波波冰",
                        "sname" => "爆芋泥波波冰",
                        "activity_name" => "",
                        "discount_price" => 0,
                        "show_trademark" => false,
                        "name_image" => "",
                        "activity_type" => 0,
                        "specifications" => [],
                        "attributes" => [],
                        "materials" => [
                            [
                                "material_id" => 409,
                                "name" => "常规吸管",
                                "price" => "0.00",
                                "material_group_id" => 27
                            ],
                            [
                                "material_id" => 230,
                                "name" => "\u6709\u828b\u5934\u9897\u7c92(\u63a8\u8350)",
                                "price" => "0.00",
                                "material_group_id" => 12
                            ],
                            [
                                "material_id" => 149,
                                "name" => "\u6807\u51c6\uff08\u63a8\u8350\uff09",
                                "price" => "0.00",
                                "material_group_id" => 6
                            ],
                            [
                                "material_id" => 140,
                                "name" => "\u51b0\u6c99\uff08\u63a8\u8350\uff09",
                                "price" => "0.00",
                                "material_group_id" => 5
                            ],
                            [
                                "material_id" => 379,
                                "name" => "\u6b63\u5e38\u7cd6(\u63a8\u8350)",
                                "price" => "0.00",
                                "material_group_id" => 4
                            ],
                            [
                                "material_id" => 558,
                                "name" => "\u6b63\u5e38(\u63a8\u8350)",
                                "price" => "0.00",
                                "material_group_id" => 3
                            ]
                        ],
                        "image" => "https://go.cdn.heytea.com/product/2019/08/02/tmp/a5a9bdd8b9db4b37a6d20df8e1aedf87.jpg"
                    ]
                ],
                "shop" => [
                    "id" => 28,
                    "name" => "万象天地PINK店",
                    "contact_phone" => "0755-86681153",
                    "contact_name" => "喜茶君",
                    "province" => "\u5e7f\u4e1c\u7701",
                    "city" => "\u6df1\u5733\u5e02",
                    "city_code" => "156440300",
                    "district" => "\u5357\u5c71\u533a",
                    "address" => "\u534e\u6da6\u4e07\u8c61\u5929\u5730SL187\u53f7\u5546\u94fa",
                    "latitude" => "22.541500",
                    "longitude" => "113.955292",
                    "min_charge" => 30,
                    "distance" => 0,
                    "delivery_distance" => 3000,
                    "support_mt_takeaway" => 1,
                    "support_sf_takeaway" => 0,
                    "support_td_takeaway" => 0,
                    "support_jd_takeaway" => 0,
                    "scene_code" => "http://go.heytea.com/storage/shop/scene_code/shop_id_28.png",
                    "tips" => "15",
                    "limit_cup" => 10,
                    "takeaway_limit_cup" => "5",
                    "location_city" => null,
                    "disable_order_type" => 0,
                    "country" => "\u4e2d\u56fd",
                    "country_code" => "156",
                    "district_code" => "440305",
                    "support_cash" => 1,
                    "nearby_shop_count" => 0,
                    "is_current_city" => null,
                    "is_support_premade" => 0,
                    "currency" => 1,
                    "estimate_time_type" => 1,
                    "appointable" => null
                ],
                "delivery" => null
            ]
        ];
        return $orderList;
    }

    public function getOrderDetail()
    {
        $detail = [
            "reason" => "协商一致退款",
            "open_pickupPage_expectTime" => 1,
            "gather_feedback" => false,
            "pickup_code_qrcode" => "http://go.heytea.com/orders/755015201910201229255435/puckupNo",
            "spell_unique_id" => "",
            "delivery_fee" => "0.00",
            "prior" => 0,
            "pickup_type" => "自提",
            "total_fee" => 33.00,
            "payment" => "33.00",
            "id" => 55596826,
            "is_takeaway" => false,
            "alipay_invoice_button" => true,
            "set_items" => [],
            "refund_status" => "NO_REFUND",
            "invoice_successed" => false,
            "new_order_invoice" => false,
            "paid_at" => "2019-10-20 12=>29=>29",
            "currency_type" => "CNY",
            "coupon_fee" => "0.00",
            "showPaymentDetails" => false,
            "pickup_time" => "2019-10-20 14=>00=>47",
            "items" => [[
                "activity_name" => "",
                "images" => [
                    "data" => [[
                        "id" => 88364,
                        "url" => "https://go.cdn.heytea.com/storage/product/2019/11/12/5ad4996d0fdd4f3a85a25b8fe95a4db8.jpg"
                    ],
                        [
                            "id" => 121233,
                            "url" => "https://go.cdn.heytea.com/storage/product/2020/03/11/78ad5460e80d4587a8f07abc4baf76e9.jpg"
                        ]
                    ]
                ],
                "quantity" => 1,
                "discount_price" => 0,
                "sku_id" => 1186,
                "specifications" => [
                    "data" => []
                ],
                "name_image" => "",
                "show_trademark" => false,
                "category_id" => 20,
                "materials" => [[
                    "material_group_id" => 3,
                    "price" => "0.00",
                    "name" => "加热(推荐)",
                    "material_id" => 41
                ]],
                "price" => "10.00",
                "sname" => "流沙牛角",
                "product_id" => 161,
                "total_fee" => "10.00",
                "activity_type" => 0,
                "name" => "流沙牛角",
                "attributes" => [
                    "data" => []
                ],
                "id" => 100194060
            ],
                [
                    "activity_name" => "",
                    "images" => [
                        "data" => [[
                            "id" => 64565,
                            "url" => "https://go.cdn.heytea.com/product/2019/08/02/tmp/a5a9bdd8b9db4b37a6d20df8e1aedf87.jpg"
                        ],
                            [
                                "id" => 116583,
                                "url" => "https://go.cdn.heytea.com/storage/product/2020/03/03/436ce2f2b562478bae451aefed7a0c97.jpg"
                            ]
                        ]
                    ],
                    "quantity" => 1,
                    "discount_price" => 0,
                    "sku_id" => 1373,
                    "specifications" => [
                        "data" => []
                    ],
                    "name_image" => "",
                    "show_trademark" => false,
                    "category_id" => 11,
                    "materials" => [[
                        "material_group_id" => 27,
                        "price" => "0.00",
                        "name" => "常规吸管",
                        "material_id" => 409
                    ],
                        [
                            "material_group_id" => 12,
                            "price" => "0.00",
                            "name" => "有芋头颗粒(推荐)",
                            "material_id" => 230
                        ],
                        [
                            "material_group_id" => 6,
                            "price" => "0.00",
                            "name" => "标准（推荐）",
                            "material_id" => 149
                        ],
                        [
                            "material_group_id" => 5,
                            "price" => "0.00",
                            "name" => "冰沙（推荐）",
                            "material_id" => 140
                        ],
                        [
                            "material_group_id" => 4,
                            "price" => "0.00",
                            "name" => "正常糖(推荐)",
                            "material_id" => 379
                        ],
                        [
                            "material_group_id" => 3,
                            "price" => "0.00",
                            "name" => "正常(推荐)",
                            "material_id" => 558
                        ]
                    ],
                    "price" => "23.00",
                    "sname" => "爆芋泥波波冰",
                    "product_id" => 514,
                    "total_fee" => "23.00",
                    "activity_type" => 0,
                    "name" => "爆芋泥波波冰",
                    "attributes" => [
                        "data" => []
                    ],
                    "id" => 100194061
                ]
            ],
            "status" => "TRADE_CLOSED",
            "no" => "755015201910201229255435",
            "hidden_invoice" => false,
            "shop" => [
                "support_jd_takeaway" => 0,
                "is_support_premade" => 0,
                "country" => "中国",
                "contact_phone" => "0755-86681153",
                "distance" => 0,
                "city" => "深圳市",
                "latitude" => "22.541500",
                "limit_cup" => 10,
                "disable_order_type" => 0,
                "city_code" => "156440300",
                "support_cash" => 1,
                "tips" => "15",
                "province" => "广东省",
                "appointable" => null,
                "location_city" => null,
                "currency" => 1,
                "id" => 28,
                "min_charge" => 30,
                "longitude" => "113.955292",
                "nearby_shop_count" => 0,
                "contact_name" => "喜茶君",
                "address" => "华润万象天地SL187号商铺",
                "is_current_city" => null,
                "estimate_time_type" => 1,
                "takeaway_limit_cup" => "5",
                "support_td_takeaway" => 0,
                "delivery_distance" => 3000,
                "country_code" => "156",
                "support_mt_takeaway" => 1,
                "support_sf_takeaway" => 0,
                "district_code" => "440305",
                "district" => "南山区",
                "name" => "万象天地PINK店",
                "scene_code" => "http://go.heytea.com/storage/shop/scene_code/shop_id_28.png"
            ],
            "activity" => [],
            "box_fee" => "0.00",
            "called_at" => "2019-10-20 12=>51=>15",
            "created_at" => "2019-10-20 12=>29=>25",
            "is_can_refund" => false,
            "outer_id" => null,
            "discount_fee" => "0.00",
            "order_detail_qrcode" => "https://go.heytea.com/device/755015201910201229255435/order",
            "pickup_time_period_show" => null,
            "making_order_count" => 0,
            "is_premade" => false,
            "tax_fee" => "-1",
            "coupon_library_id" => "",
            "is_comment" => 2,
            "currency" => 1,
            "order_channel" => "W",
            "show_remind_button" => 0,
            "only_vip_show_invoice" => false,
            "delivery" => null,
            "cupboard" => null,
            "need_wait_time" => 0,
            "cancelCountdown" => 0,
            "pickup_no" => "8114",
            "takeaway_time_immediately_show" => "2019-10-20 13=>14=>29",
            "pickup_time_period" => "",
            "trade_type" => "JSAPI",
            "remarks" => "不打包"
        ];
        return $detail;
    }
}